module.exports = {
    Version: '1.0',
    FileExtension: ".ts",
    ComponentFileExtension: ".tsx",
    ProjectPath: "../src",
    ConfigsPath: "../src/App/Config",
    InterfacesPath: "../src/App/Interfaces",
    TypesPath: "../src/App/Types",
    FunctionsPath: "../src/App/Functions",
    HooksPath: "../src/App/Hooks",
    MiddlewaresPath: "../src/App/Middlewares",
    ServiceProvidersPath: "../src/App/Services/Providers",
    StoresPath: "../src/App/WaterTank/Stores",
    ActionsPath: "../src/App/WaterTank/Actions",
    ComponentsPath: "../src/Components/Core",
    LayoutsPath: "../src/Components/Layouts",
    ScreensPath: "../src/Components/Screens",
    ViewsPath: "../src/Views",
    StyleSheetsPath: "../src/Static/StyleSheets",
};
