DROP FUNCTION IF EXISTS getProductTotalSales;

DELIMITER $$
CREATE FUNCTION getProductTotalSales(PRODUCT_UUID TEXT CHARACTER SET 'utf8mb4') RETURNS INT
BEGIN
    DECLARE TOTAL INT;
    SET TOTAL = 0;

    SELECT * FROM (SELECT SUM(SOP.quantity) FROM sales_order_particulars SOP WHERE SOP.product_uuid = PRODUCT_UUID COLLATE utf8mb4_unicode_ci) SOP_TOTAL INTO TOTAL;

    RETURN IF(TOTAL IS NULL, 0, TOTAL);
END$$
DELIMITER ;
