export interface ICustomer {
    id: number,
    uuid: string,
    code: string,
    name: string ,
    dropdown_label?: string | null,
    area_code: string ,
    address: string ,
    profile_image_uri: string ,
    total_orders: number,
    total_order_amount: number,
    due: number,
    paid: number,
    phone_number: string ,
    email:  string ,
    password:  string ,
    status: "Active" | "Inactive" |  "Banned" | "Pending",
    ip: string | null,
    agent: string | null,
    is_deleted: boolean | number,
    created_by_uuid: string | null,
    updated_by_uuid: string | null,
    deleted_by_uuid: string | null,
    created_at: string | null,
    updated_at: string | null,
    deleted_at: string | null,
}