import {IIngredient} from "@/App/Interfaces/Models/Ingredient.Interface";

export interface IIngredientPurchaseParticular {
    id: number,
    uuid: string,
    ingredient_purchase_uuid: string,
    ingredient_uuid: string,
    ingredient_code: string,
    ingredient_name: string,
    quantity: number,
    unit_price: number,
    total_price: number,
    discount: number,
    net_price: number,
    ip: string | null,
    agent: string | null,
    is_deleted: boolean | number,
    created_by_uuid: string | null,
    updated_by_uuid: string | null,
    deleted_by_uuid: string | null,
    created_at: string | null,
    updated_at: string | null,
    deleted_at: string | null,
    ingredient: IIngredient,
}