import {ICustomer} from "@/App/Interfaces/Models/Customer.Interface";
import {ISalesOrderParticulars} from "@/App/Interfaces/Models/SalesOrderParticulars.Interface";

export interface ISalesOrder {
    id: number,
    uuid: string,
    code: string,
    customer_uuid: string,
    date: string,
    total_amount: number,
    discount: number,
    payable_amount: number,
    received_amount: number,
    return_amount: number,
    due_amount: number,
    paid_amount: number,
    vat: number,
    tax: number,
    payment_type: 'Cash' | 'Credit',
    status: "Active" | "Inactive" | "Pending",
    sales_type: "Parcel" | "Table_Sale",
    user_uuid: string | null,
    ip: string | null,
    agent: string | null,
    is_deleted: boolean | number,
    created_by_uuid: string | null,
    updated_by_uuid: string | null,
    deleted_by_uuid: string | null,
    created_at: string | null,
    updated_at: string | null,
    deleted_at: string | null,
    customer: ICustomer,
    particulars: ISalesOrderParticulars[],
}