export interface IStoreInformation {
    id: number,
    uuid: string,
    code: string,
    name: string | null,
    slogan: string | null,
    about: string | null,
    logo_uri: string | null,
    banner_uri: string | null,
    website: string | null,
    email: string | null,
    phone_1: string | null,
    phone_2: string | null,
    address_one: string | null,
    address_two: string | null,
    address_three: string | null,
    division_id: number,
    district_id: number,
    upazila_id: number,
    zip_code: string | null,
    post_office: string | null,
    ip: string | null,
    agent: string | null,
    created_by_uuid: string | null,
    updated_by_uuid: string | null,
    created_at: string | null,
    updated_at: string | null,
    deleted_at: string | null,
}