export interface ISupplier {
    id: number,
    uuid: string,
    code: string,
    full_name: string | null,
    dropdown_label?: string | null,
    area_code: string | null,
    address: string | null,
    profile_image_uri: string | null,
    phone_number: string | null,
    email:  string | null,
    password:  string | null,
    status: "Active" | "Inactive" |  "Banned" | "Pending",
    ip: string | null,
    agent: string | null,
    is_deleted: boolean | number,
    created_by_uuid: string | null,
    updated_by_uuid: string | null,
    deleted_by_uuid: string | null,
    created_at: string | null,
    updated_at: string | null,
    deleted_at: string | null,
}